language: ruby
rvm:
  - 1.9.3
  - 2.0.0
env:
  - PUPPET_VERSION=3.3.0
  - PUPPET_VERSION=3.4.0
  - PUPPET_VERSION=3.5.0
  - PUPPET_VERSION=3.6.0
  - PUPPET_VERSION=3.7.0
gemfile: Gemfile.travis
before_install: 'cp Gemfile Gemfile.travis'
notifications:
  email:
    - 'inkblot@movealong.org'
